### ISSUE TITLE
HTTP "Content-Type" of "audio/mpeg" is not supported in firefox

### ISSUE THREAD

**Issue by c-fos** [makc/fps-three.js#1]
Loading of "http://makc.github.io/fps-three.js/" hangs because Firefox 31 can`t download mpeg audio files.
There is a message from my web console:
'HTTP "Content-Type" of "audio/mpeg" is not supported. Load of media resource http://makc.github.io/fps-three.js/assets/sounds/shotgunFired.mp3 failed.'

Please fix this error, or check browser and disable audio content for such cases.

**Comment by makc** [comment]
It's funny it works in my Firefox 31. It is [said](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) that "The MP3 audio format (.mp3, audio/mpeg; ...) is supported in &lt;audio&gt; by Firefox/Firefox for Android/Firefox OS when the operating system provides an MP3 decoder". So, what is your OS? It might help if you give me your [user agent](http://www.whatsmyuseragent.com/).

**Comment by makc** [comment]
Also, please [open this jsfiddle](http://jsfiddle.net/n6VJ4/) and report the result. Thank you.

**Comment by c-fos** [comment]
I`m sorry, it was my mistake. I haven`t GStreamer plugins installed in my OS.
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
jsfiddle: "false"

**Comment by makc** [comment]
No, I think it's reasonable request. You can't have this without textures, but it might still be okay without sounds.

Also I think I should alert() failure message.

**Comment by amir-ytel** [comment]
ASASASASASASA
